import React, { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import BrandLogos from 'components/BrandLogos';
import Shelf from 'components/Shelf';

import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { fetchBrand } from 'commands';

const Home: NextPage = () => {
  const [brandCode, setBrandCode] = useState('utools');

  const selectBrandCode = (b: string) => () => { setBrandCode(b);};

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BrandLogos brandCode={brandCode} selectBrandCode={selectBrandCode}></BrandLogos>
        <Shelf brandCode={brandCode} fetchBrand={fetchBrand}/>
      </main>
    </div>
  );
};

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}

export async function getStaticPaths() {
  const paths = [
    { params: { brand: 'utools', category: 'all', page: '1' } },
    { params: { brand: 'stabila', category: 'all', page: '1' } },
    { params: { brand: 'utools', category: 'all', page: '1' }, locale: 'en' },
    { params: { brand: 'stabila', category: 'all', page: '1' }, locale: 'en' },
  ];

  return { paths, fallback: false };
}

export default Home;
